feat(mailchimp): add campaigns to "Newspack" folder
Automattic/newspack-newsletters pull request #1075
Opened 2023-01-31 18:05 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces support for Mailchimp folders. Every campaign authored through the plugin will be set to the "Newspack" folder.

### How to test the changes in this Pull Request:

1. Make sure you have Mailchimp configured as your ESP
2. Draft a new newsletter and save
3. Visit your Mailchimp dashboard and confirm the folder has been created with the draft
4. Draft another newsletter and save
5. Confirm in the dashboard that it's inside the recently created folder.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-01-31 18:42 UTC, miguelpeixe commented
Switching to draft in order to support selecting different folders per campaign

2023-02-13 11:15 UTC, adekbadek requested changes
Found one issue – the folder cannot be un-set. After selecting a folder, then selecting "No folder", the API request is made without the folder id and thus fails. 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/7383192/218443518-0b6f15e6-8d2c-454c-bfdc-a6de2c0e765b.png">

2023-02-14 15:37 UTC, miguelpeixe commented
Thank you for catching that! This was a bug on the endpoint code but also Mailchimp doesn't allow a campaign to be _folderless_ once it's attached to a folder.

13ab54ef5e3448141a7fe6364850eb70230bd201 tweaks the endpoint code so it doesn't rely on unnecessary regex to function and removes the "No folder" option once a folder is selected since it's unsupported.

2023-02-15 11:42 UTC, adekbadek approved these changes

2023-02-16 09:56 UTC, merged