feat: optional comments support
Automattic/newspack-newsletters pull request #1170
Opened 2023-05-10 19:51 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Implements optional comments support for public newsletters.

### How to test the changes in this Pull Request:

1. Check out this branch and visit the Newsletter tab of "Newspack -> Engagement"
2. Confirm you see the new checkbox for `Support comments in public newsletters posts`
3. Toggle it on
4. Send/publish a new newsletter set to public
5. Confirm the "Discussion" panel is available and comments can be toggled on and off
6. Toggle it on and save
7. Visit the post and confirm comments are available
8. Visit the Newsletters settings outside Newspack's wizard (Newsletters -> Settings)
9. Confirm you see the same field
10. Toggle it off and save
11. Refresh the post page and confirm comments are no longer available

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-05-16 18:16 UTC, laurelfulford requested changes
Steps 1-9 looked good to me! 

When I got to steps 10 and 11 and tried turning off comments for Newsletters (both in the wizard and in the Newsletters > Settings screen), it didn't work as described. Comments were not enabled for new newsletters, but they also were not removed from already-published newsletters. 

To me, this _does_ make sense with how WordPress comments work: you can enable them for new posts and have them close after a certain period of time, but disabling them for new posts does not remove the comment form from posts that already have it. It's just might not be super clear to users what's happening. 

I also tested this option with the WordPress commenting options (under Settings > Discussion) and they also worked as expected to me, but it might be unexpected for users. For example, if comments are not enabled for new posts under Settings > Discussion, they also won't work on the Newsletters.

I don't think any of the above needs to be changed personally, but I think tweaking the label might help explain that the newsletter commenting is tied to the WordPress comment settings. What do you think about changing the label to, "Enable the post comment settings on newsletters", and include a link to the Settings > Discussion screen?

2023-05-17 19:59 UTC, leogermani commented
I experienced the same behavior as Laurel. When you disable the post type support for comments, posts that had comments enable will remain with them until you edit and save them again.

I wasn't going to say anything but maybe a label change as Laurel suggests is a good idea.

What about "Allow comments to be enabled for public Newsletters"

Not sure this will make any difference though, so I'll leave the PR pre-approved (code looks good btw)

2023-05-23 13:51 UTC, miguelpeixe commented
Thanks! I changed the phrasing to "Allow comments to be enabled for public Newsletters" and I think it better reflects the action.

2023-05-26 17:46 UTC, laurelfulford approved these changes
Thanks Miguel! Looks good to me! 🙌

2023-05-26 19:05 UTC, merged