fix: buttons' border radius, width, padding and colors
Automattic/newspack-newsletters pull request #1276
Opened 2023-09-12 16:02 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes button block support for:

 - Border radius
 - Text color
 - Background color
 - Padding
 - Width
 
| Editor | Rendered markup |
| --- | --- |
|  <img width="552" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/a8cd93d8-7034-4855-bca4-51299f64fb3e"> |  <img width="576" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/3336d239-9f06-495e-b3e1-3bb1e6ccec62"> |

### How to test the changes in this Pull Request:

1. Draft a new newsletter and add a button block
2. Style the button block with custom values for all the style attributes listed above
3. Save and click to preview the newsletter
4. Confirm the preview markup reflects the editor styles
5. Send the newsletter and confirm it also renders as expected

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2023-09-13 18:13 UTC, dkoo requested changes
All is working as described except for the width attribute. The button doesn't appear consistent in the editor vs. in the preview and the sent email. This is true of any width setting.

In the editor, at 50%:

<img width="1259" alt="Screenshot 2023-09-13 at 12 11 02 PM" src="https://github.com/Automattic/newspack-newsletters/assets/2230142/1395d14a-b4c0-45eb-969e-403ca734fe19">

In the sent email:

<img width="633" alt="Screenshot 2023-09-13 at 12 11 09 PM" src="https://github.com/Automattic/newspack-newsletters/assets/2230142/90047c4b-e00d-4773-8677-443ae8bc54fc">

2023-09-13 18:13 UTC, dkoo commented on includes/class-newspack-newsletters-renderer.php
> +			$preset = end( explode( '|', $value ) );
Nit: the use of the `explode` function inside `end` is causing a PHP notice.

```suggestion
			$preset_key = explode( '|', $value );
			$preset     = end( $preset_key );
```

2023-09-15 13:26 UTC, miguelpeixe commented
> All is working as described except for the width attribute. The button doesn't appear consistent in the editor vs. in the preview and the sent email. This is true of any width setting.

That seems like a limitation with MJML when inheriting styles from the parent column layout. When adding a single button the width works well, see `Button #3` in the example below:

| Editor | Rendered |
| --- | --- |
| <img width="602" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/bf4a0d33-fee0-4ca3-9ecb-02de5cb24bf1"> | <img width="519" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/820752/4e577d24-3dc3-4deb-a733-e16fb1c279f6"> |

Not sure how to overcome this since there are no classes to allow a custom CSS to tweak this...

2023-09-15 17:19 UTC, dkoo commented
@miguelpeixe I think I got it working: https://github.com/Automattic/newspack-newsletters/pull/1285

The width, if defined, should be applied to the button's `mj-column` container. If not defined, then we still need to manually define a width, otherwise MJML will default to 50%. Let me know if that tweak works.

2023-09-15 17:52 UTC, dkoo approved these changes
Looking good to me now!

2023-09-15 17:55 UTC, merged

2023-09-15 17:57 UTC, miguelpeixe commented
@dkoo I merged with the co-authoring message but it seems it didn't work for some reason 😕