fix: respect buttons alignment
Automattic/newspack-newsletters pull request #1492
Opened 2024-04-25 19:23 UTC by chickenn00dle

### All Submissions:

* [ ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [ ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR fixes an issue where we were forcing buttons to always be centered aligned, even when alignment was set otherwise in the Newsletter editor:

![Screenshot 2024-04-25 at 15 19 23](https://github.com/Automattic/newspack-newsletters/assets/17905991/6af0065a-6dc7-400e-8443-50181e30ea89)

### How to test the changes in this Pull Request:

1. Create a new newsletter
2. Add a buttons block with one or more buttons
3. Set the alignment to something other than center
4. On `trunk` the buttons will not respect the buttons alignment settings. On this branch it will.
5. Preview the email
6. On `trunk` the buttons in the email will not respect the buttons alignment settings. On this branch it will.

Note: There is a limitation with spacing in the mjml library we use to generate emails since the width cannot be variable in the output. That said, this issue is still present on `trunk`. This PR only allows us to align the buttons (with spacing) properly.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-04-26 17:59 UTC, chickenn00dle commented on tests/test-renderer.php
> +			'<mj-section url="https://www.amazon.com/Learning-PHP-MySQL-JavaScript-Javascript/dp/1491978910" padding="0"><mj-column padding="12px" width="100%"><mj-text padding="0" line-height="1.5" font-size
This is unrelated to my changes, but was causing phpunit tests to fail so I updated.

2024-05-08 12:29 UTC, adekbadek requested changes
When testing, I've inserted three Buttons blocks, each with one Button block, aligned left, center, and right. In the editor it looks ok:

<img width="721" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/7383192/0731499c-003a-4fa6-ba8c-a75f210d6b98">

but the sent email has a misalignment:

<img width="641" alt="image" src="https://github.com/Automattic/newspack-newsletters/assets/7383192/a0c4df1f-732a-4fe9-924c-03132e622a40">

2024-05-09 14:45 UTC, chickenn00dle commented
Thanks for the review @adekbadek!

> When testing, I've inserted three Buttons blocks, each with one Button block, aligned left, center, and right. In the editor it looks ok

Good catch. Looks like I was defaulting to center alignment when no alignment is set for the buttons block, when this should default to left: https://github.com/Automattic/newspack-newsletters/pull/1492/commits/c0d0e4db17767a6180420cc3f5830aa58212c2aa

This should do the trick:
![Screenshot 2024-05-09 at 10 45 06](https://github.com/Automattic/newspack-newsletters/assets/17905991/38cade2b-1b11-4855-915b-015e0b6e2526)

2024-05-09 15:30 UTC, chickenn00dle commented
Also noting I've added some unit tests: https://github.com/Automattic/newspack-newsletters/pull/1492/commits/ec8ab8c643452e3ef4b8c368e861ae9c845ef158

2024-05-10 06:40 UTC, adekbadek approved these changes

2024-05-10 14:44 UTC, merged