feat: add new modern style variation to block and set it to default
Automattic/newspack-newsletters pull request #1513
Opened 2024-05-21 14:25 UTC by thomasguillot

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR introduces a new style variation (SV) to the Newsletter Subscription Form block. The new SV, "Modern", will be the default, meaning all newly inserted blocks will use this style. The previous style has been retained and renamed as "Classic" to ensure backwards compatibility.

This SV is based on our Newspack Components and is designed to match the rest of our reader-facing UI.

![subscription-block-eg](https://github.com/Automattic/newspack-newsletters/assets/177929/46801b05-c276-4e0a-b5bd-ec8ca57db494)

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Add the block to a page
3. Play with the settings (and preview front-end)
4. Test the SVs.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-05-22 20:48 UTC, chickenn00dle requested changes
The style changes look good, but I am running into an issue where the block is showing modern as the selected style but actually defaulting to classic styles initially until I toggle between the styles one time. Here is a screen recording:

https://github.com/Automattic/newspack-newsletters/assets/17905991/191e3344-6324-4cfa-8bd5-2b83ec65e152

2024-05-22 21:24 UTC, thomasguillot commented
> I am running into an issue where the block is showing modern as the selected style but actually defaulting to classic styles initially until I toggle between the styles one time.

@chickenn00dle this is super weird. I'm not able to replicate this bug. Any idea?

2024-05-22 21:40 UTC, chickenn00dle commented
>  I'm not able to replicate this bug. Any idea?

Hmm. Another step I missed was this happens when I only have one list selected at first when the block is added to the page, and then I toggle on a second list. This bit is also shown in the video. So for clarity, here are my steps:

1. Add the newsletter subscription block to a page
2. In block settings, select a second list from the Subscriptions Lists menu:
![Screenshot 2024-05-22 at 17 38 12](https://github.com/Automattic/newspack-newsletters/assets/17905991/ecce1ed4-5bd0-4d15-ada0-060476d7eda9)
3. the newsletter options appear with classic styles in the block despite modern being the styles selection
4. select the classic style from the block settings
5. select the modern style again from block settings
6. the newsletter options now appear with modern styles as expected

This happens on the latest version of Firefox for me.

2024-05-23 13:54 UTC, thomasguillot commented
@chickenn00dle thank you very much. I was able to replicate this issue (I didn't notice it at first because my site was using system font so with one list, there was 0 difference between the 2 SV).

As a "fix" I simply removed `isDefault` from the Modern SV. I'm not quite sure why it's not being respected.

https://github.com/Automattic/newspack-newsletters/pull/1513/commits/b9b6b3475cd3e5560cab9a96fa759540f7b7441e

2024-05-23 14:48 UTC, chickenn00dle approved these changes
> As a "fix" I simply removed isDefault from the Modern SV. I'm not quite sure why it's not being respected.

This works!

Although I would suggest opening a new Asana task for digging into changing the default if the intention is to have modern be the new default.

In any case, nice work! Giving this a thumbs up 👍

2024-05-23 15:10 UTC, thomasguillot commented
> Although I would suggest opening a new Asana task for digging into changing the default if the intention is to have modern be the new default.

Good idea. We will need to do the same for the Donate block anyway.

2024-05-23 15:13 UTC, merged