fix: refactor for updating dependencies in newspack-scripts
Automattic/newspack-newsletters pull request #1530
Opened 2024-06-14 23:10 UTC by dkoo

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Refactoring required for changes in https://github.com/Automattic/newspack-scripts/pull/209. Note that this PR will not pass CI tests and should NOT be merged until https://github.com/Automattic/newspack-scripts/pull/209 is released as an NPM package, so this repo can install it as a dependency.

### How to test the changes in this Pull Request:

Follow instructions in https://github.com/Automattic/newspack-scripts/pull/209.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2024-06-20 21:00 UTC, chickenn00dle requested changes, later dismissed
Haven't gotten the chance to smoke test this one yet, but will go ahead and submit a first round of review since I'm ending my day soon and ran into some issues with the `npm` commands

2024-06-20 21:00 UTC, chickenn00dle commented on package.json
> +		"test": "newspack-scripts test",
Running this, I get the following output:

```
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /Users/raz/Sites/newspack/newsletters
  397 files checked.
  testMatch: /Users/raz/Sites/newspack/newsletters/**/*test.js?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 397 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
```

Looks like there are tests in the repo though.

2024-06-20 21:00 UTC, chickenn00dle commented on package.json
> +		"format:js": "newspack-scripts wp-scripts format '**/{src,includes}/**/*.{js,jsx,ts,tsx}'",
Same question as in other repos: running this changes alot of files despite lint passing. Is this expected?

2024-06-20 21:00 UTC, chickenn00dle commented on package.json
> +		"typescript:check": "newspack-scripts typescript-check",
tcs help is included in the output when running this. Not sure if this is expected or if perhaps the command is being called incorrectly by the script for some reason?

![Screenshot 2024-06-20 at 16 55 46](https://github.com/Automattic/newspack-newsletters/assets/17905991/f6a3de8b-b14d-4209-862f-a1e033ef3488)

2024-06-20 21:46 UTC, dkoo commented on package.json
> +		"test": "newspack-scripts test",
Ah, there are no JS Jest tests in this repo. We can probably remove this script from repos that lack them, or change them to simply output that there are no tests implemented (yet).

2024-06-20 21:48 UTC, dkoo commented on package.json
> +		"typescript:check": "newspack-scripts typescript-check",
Same issue as with Jest tests—there's no Typescript in this repo. We can omit or update the script for repos that lack any Typescript files.

2024-08-02 17:46 UTC, miguelpeixe approved these changes

2024-08-02 20:34 UTC, merged