fix: change allowed_block_types filter name
Automattic/newspack-newsletters pull request #498
Opened 2021-07-13 17:20 UTC by adekbadek

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Changes `allowed_block_types` filter name to `allowed_block_types_all`, since the former is deprecated in WP 5.8.

### How to test the changes in this Pull Request:

1. With WP 5.8 and on `master` branch, obsere a PHP notice about `allowed_block_types` being deprecated on post editor
2. Switch to this branch, observe the notice is not shown
3. Switch to WP <5.8, ensure the blocks are still filtered on Newsletter editor, e.g. a Jetpack Mailchimp block can't be added

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

2021-07-13 18:56 UTC, miguelpeixe requested changes
The `allowed_block_types_all` filter does not exist prior to 5.8. When switching to WP < 5.8 all the block types become available.

We might have to duplicate this filter call for legacy reasons.

I'm still not sure why, but even with this change I still see the following notice:
```
Deprecated: block_categories is deprecated since version 5.8.0! Use block_categories_all instead.
```

2021-07-13 19:02 UTC, dkoo approved these changes
Nice, I was wondering where those PHP warnings were coming from!

2021-07-13 19:04 UTC, dkoo requested changes
@miguelpeixe makes a good point about supporting WP 5.7.X, so I'll remove my approval for now until we decide one way or another. I wasn't seeing the PHP warning Miguel mentioned after switching to this branch, FWIW.

2021-07-13 19:07 UTC, miguelpeixe commented
> I wasn't seeing the PHP warning Miguel mentioned after switching to this branch, FWIW.

It's probably not related to newsletters. The plugin does not create any new block category that could trigger this warning.

2021-07-13 19:28 UTC, miguelpeixe commented
I misunderstood the usage of [`apply_filters_deprecated`](https://developer.wordpress.org/reference/functions/apply_filters_deprecated/) 🤦 . It's not a valid suggestion.

2021-07-13 19:37 UTC, dkoo commented
This is what [WP's documentation](https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#allowed_block_types_all) says about continuing to support WP versions prior to 5.7:

> Before WordPress 5.8 known as `allowed_block_types`. In the case when you want to support older versions of WordPress you might need a way to detect which filter should be used – the deprecated one vs the new one. The recommended way to proceed is to check if the `WP_Block_Editor_Context` class exists.

The question in my mind is, do we care to support WP versions prior to 5.8? All managed Newspack sites will be moved to 5.8 automatically. Continuing to support 5.7 and below would potentially benefit self-hosted sites who might be waiting to upgrade for whatever reason.

2021-07-14 09:04 UTC, adekbadek commented
> Continuing to support 5.7 and below would potentially benefit self-hosted sites who might be waiting to upgrade for whatever reason.

I'd follow core in this respect - if the legacy filter is deprecated, let's not support it. If the block filter won't work, and the user inserts an unsupported block, they will likely catch this issue when viewing a test email - the potential for disruption is minimal.

2021-07-14 12:14 UTC, miguelpeixe approved these changes

2021-07-14 20:18 UTC, dkoo approved these changes
> I'd follow core in this respect - if the legacy filter is deprecated, let's not support it. If the block filter won't work, and the user inserts an unsupported block, they will likely catch this issue when viewing a test email - the potential for disruption is minimal.

I'm okay this this. Should we consider posting a blog post about things like this that might work differently in WP 5.7 vs 5.8 or no longer be supported in our plugins after the 5.8 release?

2021-07-15 08:54 UTC, adekbadek commented
> Should we consider posting a blog post about things like this that might work differently in WP 5.7 vs 5.8 or no longer be supported in our plugins after the 5.8 release?

Are there more features that would not work in <5.8?

In the case of this plugin, let's add a note in release notes.

2021-07-15 08:55 UTC, merged