Fix: refactor constant contact provider (in progress)
Automattic/newspack-newsletters pull request #519
Opened 2021-07-23 18:05 UTC by miguelpeixe

### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

WIP!

Closes #503.
Closes #511.
Closes #512.

### How to test the changes in this Pull Request:

1.
2.
3.

### Other information:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-07-29 18:09 UTC, dkoo requested changes
This is impressive work on such a short timeline! After reauthenticating, the integration is working as described. I like how you handle the OAuth flow right in the Newsletter editor sidebar—makes it feel as frictionless as possible, especially since you should only need to do this once. 

I tested: 

- Creation of new drafts
- Sending test emails
- Sending live emails
- Scheduling live emails

All worked in the end, although as discussed when I tried to send my first draft, I ran into trouble due to missing physical address info on my CC account. After updating my account info, the draft remained unsendable because the error info is saved on the draft campaign even after the account is updated. This should theoretically be fixed by 00874de, which sends physical address info with every send request, but I'm unable to verify at the moment because the original draft is no longer syncing to CC and my CC account is no longer in a state which would trigger the error. Still, this is not a blocker since the issue can be bypassed by copying the newsletter content into a brand new draft, which can be sent without issue.

I ran into a couple of PHP warnings, details below. After fixing those, this can be merged.

2021-07-29 18:18 UTC, miguelpeixe commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
>  				$initial_email_address = $verified_email_addresses[0]->email_address;
This is most likely due to `array_filter` not reindexing the array values. I'll call `array_values` on the filtered result so we can ensure that `[0]` exists.

2021-07-29 18:20 UTC, miguelpeixe commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
> +		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
Yes. We should also bail sync on autosaves for other ESPs, there's no need for these extra API calls if we sync before every send/test.

2021-07-29 18:24 UTC, miguelpeixe commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
> +		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
Just filed #524 for this.

2021-07-29 18:30 UTC, miguelpeixe commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
>  				$initial_email_address = $verified_email_addresses[0]->email_address;
Please verify if 17deab4440b618ccc71c1a1d76d0c78a4fb8a064 fixes the issue.

2021-07-29 18:31 UTC, miguelpeixe commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
>  		$this->sync( $post );
This most likely is also fixed by 17deab4440b618ccc71c1a1d76d0c78a4fb8a064. The non-object is the missing `[0]` index from the filtered array.

2021-07-29 19:53 UTC, dkoo commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
> +		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
Thanks for the new issue!

2021-07-29 19:53 UTC, dkoo commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
>  		$this->sync( $post );
Yes, can confirm that this is now fixed.

2021-07-29 19:53 UTC, dkoo commented on includes/service-providers/constant_contact/class-newspack-newsletters-constant-contact.php
>  				$initial_email_address = $verified_email_addresses[0]->email_address;
Yes, can confirm that this is now fixed.

2021-07-29 19:54 UTC, dkoo approved these changes
Looking good! 🙌

2021-07-29 19:58 UTC, merged

2021-08-04 21:21 UTC, kbrown9 commented
Hi!

> Composer Autoloader update
To ensure that our Guzzle dependency does not conflict with an older version loaded from a different plugin, I'm using this autoloader by Jetpack. According to its readme:

> >This is a custom autoloader generator that uses a classmap to always load the latest version of a class.

There are some limitations to the Jetpack Autoloader that you should be aware of.

The Jetpack Autoloader can only control which version is loaded when every plugin with that dependency uses the Jetpack Autoloader. If any plugin on the site uses the dependency but does not use the Jetpack Autoloader (for example, if it uses the Composer autoloader instead), the JP Autoloader can't fully control which version gets loaded. So it's possible that you will still run into situations where an older version of Guzzle is loaded first.

I'm planning to update the Jetpack Autoloader's README to make sure this limitation is clear.

Another approach to consider is adding a custom namespace to dependencies. For example, Yoast adds a namespace to some of its dependencies, including Guzzle: https://plugins.trac.wordpress.org/browser/wordpress-seo/tags/16.8/vendor_prefixed?order=name

2021-08-06 23:00 UTC, miguelpeixe commented
Hi @kbrown9!

Thank you for sharing this with us! I filed #539 so we can better discuss the issue.